# Generated by Django 3.2 on 2021-06-08 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('user_type', models.CharField(blank=True, choices=[('agent', 'agent'), ('buyer', 'buyer'), ('admin', 'admin'), ('developer', 'developer')], max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, default='', max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='Input a valid phone number (must be 11 digits).')])),
                ('about', models.CharField(max_length=150)),
                ('accept_newsletter', models.BooleanField(default=False, verbose_name='newsletter')),
                ('avatar', models.ImageField(blank=True, upload_to=users.utils.upload_avatar_path, validators=[users.utils.validate_image])),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='is email verified')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'get_latest_by': ['date_joined'],
                'unique_together': {('email',)},
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agents', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent_profile', serialize=False, to='users.user')),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'agents',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buyer_profile', serialize=False, to='users.user')),
            ],
            options={
                'verbose_name_plural': 'buyers',
            },
        ),
    ]
