# Generated by Django 3.2 on 2021-11-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
