# Generated by Django 3.2 on 2021-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('uploaded', 'uploaded'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
