# Generated by Django 3.2 on 2021-06-08 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.PositiveIntegerField(default=1, help_text='Maximum Number of listing a user have')),
                ('premium_listing', models.PositiveIntegerField(default=0, help_text='Maximum Number of Premium listing a user have')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_code', models.CharField(max_length=40)),
                ('email_token', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='userMembershipFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.PositiveIntegerField(default=1, help_text='Maximum Number of listing a user have')),
                ('premium_listing', models.PositiveIntegerField(default=0, help_text='Maximum Number of Premium listing a user have')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('interval', models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('annually', 'annually')], max_length=10, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=100)),
                ('membership_features', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='subscription.membershipplanfeatures')),
                ('plan_code', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinValueValidator(1000)])),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
