# Generated by Django 3.2 on 2021-06-17 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershipplan',
            options={'get_latest_by': ['created_at'], 'verbose_name_plural': 'Membership Plan'},
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
