# Generated by Django 3.2 on 2021-06-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrating',
            name='sent_eligibilty',
            field=models.BooleanField(default=False),
        ),
    ]
