# Generated by Django 3.2 on 2021-06-08 10:35

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_issued_id', models.FileField(blank=True, null=True, upload_to=users.utils.upload_verification_document_path, validators=[users.utils.validate_document])),
                ('utility_bill', models.FileField(blank=True, null=True, upload_to=users.utils.upload_verification_document_path, validators=[users.utils.validate_document])),
                ('cac_document', models.FileField(blank=True, null=True, upload_to=users.utils.upload_verification_document_path, validators=[users.utils.validate_document])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('created', 'created'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='created', max_length=10)),
                ('message', models.TextField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Agent documents',
            },
        ),
    ]
