from django.urls import include, path
from . import views
from knox import views as knox_views


urlpatterns = [
    
    path('login', views.LoginAPIView.as_view()),
    path('agent-login', views.AgentLoginAPIView.as_view()),
    path('buyer-login', views.BuyerLoginAPIView.as_view()),
    path('admin-login', views.AdminLoginAPIView.as_view()),
    path('logout', knox_views.LogoutView.as_view(), name='logout'),
    #     path('logout-user', views.LogoutAPIView.as_view(), name='logout'),
    path('logoutall', knox_views.LogoutAllView.as_view(), name='logoutall'),
    #     path('logoutall', views.LogoutAllAPIView.as_view(), name='logoutall'),
    path('register-agent', views.AgentRegistrationApi.as_view(),
         name='register-agent'),
    path('register-buyer', views.BuyerRegistrationApi.as_view(),
         name='register-buyer'),
    path('register-staff', views.StaffRegistrationApi.as_view(),
         name='register-staff'),
    path('edit-profile', views.UpdateProfileView.as_view(),
         name='update-profile'),
    path('edit-staff-profile', views.UpdateStaffProfileView.as_view(),
         name='update-profile'),
    #     path('agents', views.AgentListView.as_view(),
    #          name='list-agent'),
    path('buyers', views.BuyerListView.as_view(),
         name='list-buyers'),
    path('activate-account/<int:pk>', views.activate_account,
         name='activate-account'),
    path('verify-email', views.verify_email, name="verify_user"),
    path('deactivate-account/<int:pk>', views.deactivate_account,
         name='deactivate-account'),
    path('view-profile', views.UserProfileView.as_view(),
         name='view-profile'),
    path('change-password', views.ChangePasswordView.as_view(),
         name='view-profile'),
    path('verify/<uidb64>/<token>/', views.VerificationView.as_view(),
         name='activate'),

    #     path('password_reset/',
    #          include('django_rest_passwordreset.urls', namespace='password_reset')),

    path('agents-list', views.AllAgentsApiViewSet.as_view(),
         name='list-agent'),
    path('user-monthly', views.NewUserPerMonth.as_view(),
         name='user-monthly'),
    path('staff-list', views.AllStaffApiViewSet.as_view(),
         name='list-staff'),

    path('agent/<int:agents_id>', views.GetAgentApiViewSet.as_view(),
         name='agent'),
    path('user', views.UserAPI.as_view()),
    path('agent-search', views.SearchAgentApiViewSet.as_view()),
    path('password-reset/reset_email/',
         views.RequestPasswordChange.as_view(), name='request-reset-email'),
    path('<uidb64>/<token>', views.PasswordTokenCheckApi.as_view(),
         name='password-reset-confirm'),
    path('password-reset/complete/', views.SetNewPasswordApiView.as_view(),
         name='password-reset-complete'),
    path('developer-list', views.AllDeveloperApiViewSet.as_view(),
         name='developer-list'),
    path('verify-response', views.responsePageHtml),
]
