# Generated by Django 3.2 on 2021-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('published', 'published'), ('sold', 'sold')], default='published', max_length=10),
        ),
    ]
