# Generated by Django 3.2 on 2021-06-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
