# Generated by Django 3.2 on 2021-06-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('published', 'published'), ('sold', 'sold'), ('flagged', 'flagged')], default='published', max_length=10),
        ),
    ]
