# Generated by Django 3.2 on 2021-06-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20210610_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'get_latest_by': ['-created_at'], 'verbose_name_plural': "Agents' Properties"},
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
