# Generated by Django 3.2 on 2021-06-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_property_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'get_latest_by': ['created_at'], 'verbose_name_plural': "Agents' Properties"},
        ),
    ]
