# Generated by Django 3.2 on 2021-06-24 15:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='features_fix',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, null=True, size=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, to='property.Feature'),
        ),
    ]
