# Generated by Django 3.2 on 2021-06-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_remove_property_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
