# Generated by Django 3.2 on 2021-06-25 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0011_propertyimage_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignPropertyToDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('assigned_team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.member')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_property', to='property.property')),
            ],
        ),
    ]
