# Generated by Django 3.2 on 2021-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_assignpropertytodeveloper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignpropertytodeveloper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
