# Generated by Django 3.2 on 2021-06-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_initial'),
        ('property', '0013_alter_assignpropertytodeveloper_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignpropertytodeveloper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignpropertytodeveloper',
            name='assigned_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.member'),
        ),
    ]
