# Generated by Django 3.2 on 2021-07-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20210627_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='draft_box',
            field=models.JSONField(default=dict),
        ),
    ]
