# Generated by Django 3.2 on 2021-09-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_alter_draft_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='append_to',
            field=models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('sqm', 'sqm'), ('instalment', 'instalment'), ('at once', 'at once')], max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('rent', 'Rent'), ('sell', 'Sell')], max_length=20),
        ),
    ]
