# Generated by Django 3.2 on 2021-09-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20210906_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='append_to',
            field=models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('sqm', 'sqm'), ('instalment', 'Instalment'), ('at once', 'At once')], max_length=30),
        ),
        migrations.CreateModel(
            name='DetailPropertyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.JSONField(default=dict)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
