# Generated by Django 3.2 on 2021-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20210921_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='append_to',
            field=models.CharField(choices=[('daily', 'daily'), ('monthly', 'monthly'), ('yearly', 'yearly'), ('sqm', 'sqm'), ('instalment', 'Instalment'), ('at once', 'At once'), ('outright(one-off)', 'outright(one-off)')], max_length=30),
        ),
    ]
