# Generated by Django 3.2 on 2021-10-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_property_append_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], max_length=20),
        ),
    ]
