# Generated by Django 3.2 on 2021-10-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_property_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
