# Generated by Django 3.2 on 2021-11-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_alter_property_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_preview',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
